<?php

namespace Database\Seeders;

use App\Models\Degree;
use Illuminate\Database\Seeder;

class DegreeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */


    public function run()
    {
        \DB::table('degrees')->delete();
        $degrees = [
            [
                'title' => 'Associate of Arts (AA)',
                'slug' => 'Associate of Arts (AA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Associate of Arts and Sciences (AAS)',
                'slug' => 'Associate of Arts and Sciences (AAS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'title' => 'Associate of Science (AS)',
                'slug' => 'Associate of Science (AS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'title' => 'Bachelor of Applied Science (BASc)',
                'slug' => 'Bachelor of Applied Science (BASc)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Architecture (BArch)',
                'slug' => 'Bachelor of Architecture (BArch)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Science in Information Technology',
                'slug' => 'Bachelor of Science in Information Technology',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Bachelor of Arts (BA)',
                'slug' => 'Bachelor of Arts (BA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Business Administration (BBA)',
                'slug' => 'Bachelor of Business Administration (BBA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Bachelor of Commerce (BCom)',
                'slug' => 'Bachelor of Commerce (BCom)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Bachelor of Education (BEd)',
                'slug' => 'Bachelor of Education (BEd)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Bachelor of Engineering (BEng)',
                'slug' => 'Bachelor of Engineering (BEng)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Bachelors of Software Engineering (BSE)',
                'slug' => 'Bachelors of Software Engineering (BSE)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Bachelor of Fine Arts (BFA)',
                'slug' => 'Bachelor of Fine Arts (BFA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Laws (LLB)',
                'slug' => 'Bachelor of Laws (LLB)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Medicine, Bachelor of Surgery (MBBS)',
                'slug' => 'Bachelor of Medicine, Bachelor of Surgery (MBBS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Pharmacy (BPharm)',
                'slug' => 'Bachelor of Pharmacy (BPharm)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Science (BS)',
                'slug' => 'Bachelor of Science (BS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Technology (BTech)',
                'slug' => 'Bachelor of Technology (BTech)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Accountancy (BAcc)',
                'slug' => 'Bachelor of Accountancy (BAcc)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Science in Nursing (BSN)',
                'slug' => 'Bachelor of Science in Nursing (BSN)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Computer Science (BCompSc)',
                'slug' => 'Bachelor of Computer Science (BCompSc)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Computer Applications',
                'slug' => 'Bachelor of Computer Applications',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


            ['title' => 'Bachelor of Music (BM)',
                'slug' => 'Bachelor of Music (BM)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Science in Journalism',
                'slug' => 'Bachelor of Science in Journalism',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Visual Communication Design',
                'slug' => 'Bachelor of Visual Communication Design',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => "Master's degree",
                'slug' => "Master's degree",
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Architecture (MArch)',
                'slug' => 'Master of Architecture (MArch)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of Arts (MA)',
                'slug' => 'Master of Arts (MA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Business Administration (MBA)',
                'slug' => 'Master of Business Administration (MBA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Computer Applications (MCA)',
                'slug' => 'Master of Computer Applications (MCA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Divinity (MDiv)',
                'slug' => 'Master of Divinity (MDiv)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Fine Arts (MFA)',
                'slug' => 'Master of Fine Arts (MFA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Education (MEd)',
                'slug' => 'Master of Education (MEd)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Laws (LLM)',
                'slug' => 'Master of Laws (LLM)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Library & Information Science (MLIS)',
                'slug' => 'Master of Library & Information Science (MLIS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of Philosophy (MPhil)',
                'slug' => 'Master of Philosophy (MPhil)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Commerce (MCom)',
                'slug' => 'Master of Commerce (MCom)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Public Health (MPH)',
                'slug' => 'Master of Public Health (MPH)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Science (MS)',
                'slug' => 'Master of Science (MS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Social Work (MSW)',
                'slug' => 'Master of Social Work (MSW)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Technology (MTech)',
                'slug' => 'Master of Technology (MTech)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Doctor of Engineering (DEng)',
                'slug' => 'Doctor of Engineering (DEng)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Doctor of Musical Arts (DMA)',
                'slug' => 'Doctor of Musical Arts (DMA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Bachelor of Industrial Design',
                'slug' => 'Bachelor of Industrial Design',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Doctor of Healthcare Administration (DHA)',
                'slug' => 'Doctor of Healthcare Administration (DHA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Doctor of Education (EdD)',
                'slug' => 'Doctor of Education (EdD)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Doctor of Law (JD)',
                'slug' => 'Doctor of Law (JD)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Doctor of Medicine (MD)',
                'slug' => 'Doctor of Medicine (MD)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Doctor of Pharmacy (PharmD)',
                'slug' => 'Doctor of Pharmacy (PharmD)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Doctor of Philosophy (PhD)',
                'slug' => 'Doctor of Philosophy (PhD)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => "Engineer's degree",
                'slug' => "Engineer's degree",
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Foundation degree',
                'slug' => 'Foundation degree',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Licentiate degree',
                'slug' => 'Licentiate degree',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'High school degree',
                'slug' => 'High school degree',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Doctor of Business Administration (DBA)',
                'slug' => 'Doctor of Business Administration (DBA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of public Administration (MPA)',
                'slug' => 'Master of public Administration (MPA)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


            ['title' => 'Master of Design (MDes)',
                'slug' => 'Master of Design (MDes)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of Industrial Design',
                'slug' => 'Master of Industrial Design',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


            ['title' => 'Master of Engineering (MEng)',
                'slug' => 'Master of Engineering (MEng)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Science in Project Management (MSPM)',
                'slug' => 'Master of Science in Project Management (MSPM)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of Science in Information Technology (MSc(IT))',
                'slug' => 'Master of Science in Information Technology (MSc(IT))',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of Information Technology (MIT)',
                'slug' => 'Master of Information Technology (MIT)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Philosophy (MPhil)',
                'slug' => 'Master of Philosophy (MPhil)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Computer Science (MSCS)',
                'slug' => 'Master of Computer Science (MSCS)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Mass Communication and Journalism',
                'slug' => 'Master of Mass Communication and Journalism',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Master of Educational Technology',
                'slug' => 'Master of Educational Technology',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['title' => 'Master of Accountancy (MAcc)',
                'slug' => 'Master of Accountancy (MAcc)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


            ['title' => 'Master of Music (MM)',
                'slug' => 'Master of Music (MM)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            ['title' => 'Other',
                'slug' => 'Other',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


        ];

        Degree::insert($degrees);

    }

}
