<?php

namespace Database\Seeders;

use App\Models\Timezone;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimezonesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timezones = [
            ["id" => 1 , "name"=>"Africa/Abidjan"],
            ["id" => 2 , "name"=>"Africa/Accra"],
            ["id" => 3 , "name"=>"Africa/Addis_Ababa"],
            ["id" => 4 , "name"=>"Africa/Algiers"],
            ["id" => 5 , "name"=>"Africa/Asmara"],
            ["id" => 6 , "name"=>"Africa/Bamako"],
            ["id" => 7 , "name"=>"Africa/Bangui"],
            ["id" => 8 , "name"=>"Africa/Banjul"],
            ["id" => 9 , "name"=>"Africa/Bissau"],
            ["id" => 10 , "name"=>"Africa/Blantyre"],
            ["id" => 11 , "name"=>"Africa/Brazzaville"],
            ["id" => 12 , "name"=>"Africa/Bujumbura"],
            ["id" => 13 , "name"=>"Africa/Cairo"],
            ["id" => 14 , "name"=>"Africa/Casablanca"],
            ["id" => 15 , "name"=>"Africa/Ceuta"],
            ["id" => 16 , "name"=>"Africa/Conakry"],
            ["id" => 17 , "name"=>"Africa/Dakar"],
            ["id" => 18 , "name"=>"Africa/Dar_es_Salaam"],
            ["id" => 19 , "name"=>"Africa/Djibouti"],
            ["id" => 20 , "name"=>"Africa/Douala"],
            ["id" => 21 , "name"=>"Africa/El_Aaiun"],
            ["id" => 22 , "name"=>"Africa/Freetown"],
            ["id" => 23 , "name"=>"Africa/Gaborone"],
            ["id" => 24 , "name"=>"Africa/Harare"],
            ["id" => 25 , "name"=>"Africa/Johannesburg"],
            ["id" => 26 , "name"=>"Africa/Juba"],
            ["id" => 27 , "name"=>"Africa/Kampala"],
            ["id" => 28 , "name"=>"Africa/Khartoum"],
            ["id" => 29 , "name"=>"Africa/Kigali"],
            ["id" => 30 , "name"=>"Africa/Kinshasa"],
            ["id" => 31 , "name"=>"Africa/Lagos"],
            ["id" => 32 , "name"=>"Africa/Libreville"],
            ["id" => 33 , "name"=>"Africa/Lome"],
            ["id" => 34 , "name"=>"Africa/Luanda"],
            ["id" => 35 , "name"=>"Africa/Lubumbashi"],
            ["id" => 36 , "name"=>"Africa/Lusaka"],
            ["id" => 37 , "name"=>"Africa/Malabo"],
            ["id" => 38 , "name"=>"Africa/Maputo"],
            ["id" => 39 , "name"=>"Africa/Maseru"],
            ["id" => 40 , "name"=>"Africa/Mbabane"],
            ["id" => 41 , "name"=>"Africa/Mogadishu"],
            ["id" => 42 , "name"=>"Africa/Monrovia"],
            ["id" => 43 , "name"=>"Africa/Nairobi"],
            ["id" => 44 , "name"=>"Africa/Ndjamena"],
            ["id" => 45 , "name"=>"Africa/Niamey"],
            ["id" => 46 , "name"=>"Africa/Nouakchott"],
            ["id" => 47 , "name"=>"Africa/Ouagadougou"],
            ["id" => 48 , "name"=>"Africa/Porto-Novo"],
            ["id" => 49 , "name"=>"Africa/Sao_Tome"],
            ["id" => 50 , "name"=>"Africa/Tripoli"],
            ["id" => 51 , "name"=>"Africa/Tunis"],
            ["id" => 52 , "name"=>"Africa/Windhoek"],
            ["id" => 53 , "name"=>"America/Adak"],
            ["id" => 54 , "name"=>"America/Anchorage"],
            ["id" => 55 , "name"=>"America/Anguilla"],
            ["id" => 56 , "name"=>"America/Antigua"],
            ["id" => 57 , "name"=>"America/Araguaina"],
            ["id" => 58 , "name"=>"America/Argentina/Buenos_Aires"],
            ["id" => 59 , "name"=>"America/Argentina/Catamarca"],
            ["id" => 60 , "name"=>"America/Argentina/Cordoba"],
            ["id" => 61 , "name"=>"America/Argentina/Jujuy"],
            ["id" => 62 , "name"=>"America/Argentina/La_Rioja"],
            ["id" => 63 , "name"=>"America/Argentina/Mendoza"],
            ["id" => 64 , "name"=>"America/Argentina/Rio_Gallegos"],
            ["id" => 65 , "name"=>"America/Argentina/Salta"],
            ["id" => 66 , "name"=>"America/Argentina/San_Juan"],
            ["id" => 67, "name"=>"America/Argentina/San_Luis"],
            ["id" => 68 , "name"=>"America/Argentina/Tucuman"],
            ["id" => 69 , "name"=>"America/Argentina/Ushuaia"],
            ["id" => 70, "name"=>"America/Aruba"],
            ["id" => 71 , "name"=>"America/Asuncion"],
            ["id" => 72 , "name"=>"America/Atikokan"],
            ["id" => 73 , "name"=>"America/Bahia"],
            ["id" => 74 , "name"=>"America/Bahia_Banderas"],
            ["id" => 75 , "name"=>"America/Barbados"],
            ["id" => 76 , "name"=>"America/Belem"],
            ["id" => 78 , "name"=>"America/Belize"],
            ["id" => 79 , "name"=>"America/Blanc-Sablon"],
            ["id" => 80 , "name"=>"America/Boa_Vista"],
            ["id" => 81 , "name"=>"America/Bogota"],
            ["id" => 82, "name"=>"America/Boise"],
            ["id" => 83 , "name"=>"America/Cambridge_Bay"],
            ["id" => 84 , "name"=>"America/Campo_Grande"],
            ["id" => 85 , "name"=>"America/Cancun"],
            ["id" => 86 , "name"=>"America/Caracas"],
            ["id" => 87 , "name"=>"America/Cayenne"],
            ["id" => 88 , "name"=>"America/Cayman"],
            ["id" => 89 , "name"=>"America/Chicago"],
            ["id" => 90 , "name"=>"America/Chihuahua"],
            ["id" => 91 , "name"=>"America/Costa_Rica"],
            ["id" => 92 , "name"=>"America/Creston"],
            ["id" => 93 , "name"=>"America/Cuiaba"],
            ["id" => 94 , "name"=>"America/Curacao"],
            ["id" => 95 , "name"=>"America/Danmarkshavn"],
            ["id" => 96 , "name"=>"America/Dawson"],
            ["id" => 97 , "name"=>"America/Dawson_Creek"],
            ["id" => 98 , "name"=>"America/Denver"],
            ["id" => 99 , "name"=>"America/Detroit"],
            ["id" => 100 , "name"=>"America/Dominica"],
            ["id" =>101 , "name"=>"America/Edmonton"],
            ["id" =>102 , "name"=>"America/Eirunepe"],
            ["id" =>103 , "name"=>"America/El_Salvador"],
            ["id" =>104 , "name"=>"America/Fort_Nelson"],
            ["id" =>105 , "name"=>"America/Fortaleza"],
            ["id" =>106 , "name"=>"America/Glace_Bay"],
            ["id" =>107 , "name"=>"America/Goose_Bay"],
            ["id" =>108 , "name"=>"America/Grand_Turk"],
            ["id" =>109 , "name"=>"America/Grenada"],
            ["id" =>110  , "name"=>"America/Guadeloupe"],
            ["id" =>111  , "name"=>"America/Guatemala"],
            ["id" =>112  , "name"=>"America/Guayaquil"],
            ["id" =>113  , "name"=>"America/Guyana"],
            ["id" =>114  , "name"=>"America/Halifax"],
            ["id" =>115  , "name"=>"America/Havana"],
            ["id" =>116  , "name"=>"America/Hermosillo"],
            ["id" =>117  , "name"=>"America/Indiana/Indianapolis"],
            ["id" =>118  , "name"=>"America/Indiana/Knox"],
            ["id" =>119  , "name"=>"America/Indiana/Marengo"],
            ["id" =>120  , "name"=>"America/Indiana/Petersburg"],
            ["id" =>121  , "name"=>"America/Indiana/Tell_City"],
            ["id" =>122  , "name"=>"America/Indiana/Vevay"],
            ["id" =>123  , "name"=>"America/Indiana/Vincennes"],
            ["id" =>124  , "name"=>"America/Indiana/Winamac"],
            ["id" =>125  , "name"=>"America/Inuvik"],
            ["id" =>126  , "name"=>"America/Iqaluit"],
            ["id" =>127  , "name"=>"America/Jamaica"],
            ["id" =>128  , "name"=>"America/Juneau"],
            ["id" =>129  , "name"=>"America/Kentucky/Louisville"],
            ["id" =>130  , "name"=>"America/Kentucky/Monticello"],
            ["id" =>131  , "name"=>"America/Kralendijk"],
            ["id" =>132  , "name"=>"America/La_Paz"],
            ["id" => 133 , "name"=>"America/Lima"],
            ["id" => 134 , "name"=>"America/Los_Angeles"],
            ["id" => 135 , "name"=>"America/Lower_Princes"],
            ["id" => 136 , "name"=>"America/Maceio"],
            ["id" => 137 , "name"=>"America/Managua"],
            ["id" => 138 , "name"=>"America/Manaus"],
            ["id" => 139 , "name"=>"America/Marigot"],
            ["id" => 140 , "name"=>"America/Martinique"],
            ["id" => 141 , "name"=>"America/Matamoros"],
            ["id" => 142 , "name"=>"America/Mazatlan"],
            ["id" => 143 , "name"=>"America/Menominee"],
            ["id" => 144 , "name"=>"America/Merida"],
            ["id" => 145 , "name"=>"America/Metlakatla"],
            ["id" => 146 , "name"=>"America/Mexico_City"],
            ["id" => 147 , "name"=>"America/Miquelon"],
            ["id" => 148 , "name"=>"America/Moncton"],
            ["id" => 149 , "name"=>"America/Monterrey"],
            ["id" => 150 , "name"=>"America/Montevideo"],
            ["id" => 151 , "name"=>"America/Montserrat"],
            ["id" => 152 , "name"=>"America/Nassau"],
            ["id" => 153 , "name"=>"America/New_York"],
            ["id" => 154 , "name"=>"America/Nipigon"],
            ["id" => 155 , "name"=>"America/Nome"],
            ["id" => 156 , "name"=>"America/Noronha"],
            ["id" => 157 , "name"=>"America/North_Dakota/Beulah"],
            ["id" => 158 , "name"=>"America/North_Dakota/Center"],
            ["id" => 159 , "name"=>"America/North_Dakota/New_Salem"],
            ["id" => 160 , "name"=>"America/Nuuk"],
            ["id" => 161 , "name"=>"America/Ojinaga"],
            ["id" => 162 , "name"=>"America/Panama"],
            ["id" => 163 , "name"=>"America/Pangnirtung"],
            ["id" => 164 , "name"=>"America/Paramaribo"],
            ["id" => 165 , "name"=>"America/Phoenix"],
            ["id" => 166 , "name"=>"America/Port-au-Prince"],
            ["id" => 167 , "name"=>"America/Port_of_Spain"],
            ["id" => 168 , "name"=>"America/Porto_Velho"],
            ["id" => 169 , "name"=>"America/Puerto_Rico"],
            ["id" => 170 , "name"=>"America/Punta_Arenas"],
            ["id" => 171 , "name"=>"America/Rainy_River"],
            ["id" => 172 , "name"=>"America/Rankin_Inlet"],
            ["id" => 173 , "name"=>"America/Recife"],
            ["id" => 174 , "name"=>"America/Regina"],
            ["id" => 175 , "name"=>"America/Resolute"],
            ["id" => 176 , "name"=>"America/Rio_Branco"],
            ["id" => 177 , "name"=>"America/Santarem"],
            ["id" => 178 , "name"=>"America/Santiago"],
            ["id" => 179 , "name"=>"America/Santo_Domingo"],
            ["id" => 180 , "name"=>"America/Sao_Paulo"],
            ["id" => 181 , "name"=>"America/Scoresbysund"],
            ["id" => 182 , "name"=>"America/Sitka"],
            ["id" => 183 , "name"=>"America/St_Barthelemy"],
            ["id" => 184 , "name"=>"America/St_Johns"],
            ["id" => 185 , "name"=>"America/St_Kitts"],
            ["id" => 186 , "name"=>"America/St_Lucia"],
            ["id" => 187 , "name"=>"America/St_Thomas"],
            ["id" => 188 , "name"=>"America/St_Vincent"],
            ["id" => 189 , "name"=>"America/Swift_Current"],
            ["id" => 190 , "name"=>"America/Tegucigalpa"],
            ["id" => 191 , "name"=>"America/Thule"],
            ["id" => 192 , "name"=>"America/Thunder_Bay"],
            ["id" => 193 , "name"=>"America/Tijuana"],
            ["id" => 194 , "name"=>"America/Toronto"],
            ["id" => 195 , "name"=>"America/Tortola"],
            ["id" => 196 , "name"=>"America/Vancouver"],
            ["id" => 197 , "name"=>"America/Whitehorse"],
            ["id" => 198 , "name"=>"America/Winnipeg"],
            ["id" => 199 , "name"=>"America/Yakutat"],
            ["id" => 200 , "name"=>"America/Yellowknife"],
            ["id" => 201 , "name"=>"Antarctica/Casey"],
            ["id" => 202 , "name"=>"Antarctica/Davis"],
            ["id" => 203 , "name"=>"Antarctica/DumontDUrville"],
            ["id" => 204 , "name"=>"Antarctica/Macquarie"],
            ["id" => 205 , "name"=>"Antarctica/Mawson"],
            ["id" => 206 , "name"=>"Antarctica/McMurdo"],
            ["id" => 207 , "name"=>"Antarctica/Palmer"],
            ["id" => 208 , "name"=>"Antarctica/Rothera"],
            ["id" => 209 , "name"=>"Antarctica/Syowa"],
            ["id" => 210 , "name"=>"Antarctica/Troll"],
            ["id" => 211 , "name"=>"Antarctica/Vostok"],
            ["id" => 212 , "name"=>"Arctic/Longyearbyen"],
            ["id" => 213 , "name"=>"Asia/Aden"],
            ["id" => 214 , "name"=>"Asia/Almaty"],
            ["id" => 215 , "name"=>"Asia/Amman"],
            ["id" => 216 , "name"=>"Asia/Anadyr"],
            ["id" => 217 , "name"=>"Asia/Aqtau"],
            ["id" => 218 , "name"=>"Asia/Aqtobe"],
            ["id" => 219 , "name"=>"Asia/Ashgabat"],
            ["id" => 220 , "name"=>"Asia/Atyrau"],
            ["id" => 221 , "name"=>"Asia/Baghdad"],
            ["id" => 222 , "name"=>"Asia/Bahrain"],
            ["id" => 223 , "name"=>"Asia/Baku"],
            ["id" => 224 , "name"=>"Asia/Bangkok"],
            ["id" => 225 , "name"=>"Asia/Barnaul"],
            ["id" => 226 , "name"=>"Asia/Beirut"],
            ["id" => 227 , "name"=>"Asia/Bishkek"],
            ["id" => 228 , "name"=>"Asia/Brunei"],
            ["id" => 229 , "name"=>"Asia/Chita"],
            ["id" => 230 , "name"=>"Asia/Choibalsan"],
            ["id" => 231 , "name"=>"Asia/Colombo"],
            ["id" => 232 , "name"=>"Asia/Damascus"],
            ["id" => 233 , "name"=>"Asia/Dhaka"],
            ["id" => 234 , "name"=>"Asia/Dili"],
            ["id" => 235 , "name"=>"Asia/Dubai"],
            ["id" => 236 , "name"=>"Asia/Dushanbe"],
            ["id" => 237 , "name"=>"Asia/Famagusta"],
            ["id" => 238 , "name"=>"Asia/Gaza"],
            ["id" => 239 , "name"=>"Asia/Hebron"],
            ["id" => 240 , "name"=>"Asia/Ho_Chi_Minh"],
            ["id" => 241 , "name"=>"Asia/Hong_Kong"],
            ["id" => 242 , "name"=>"Asia/Hovd"],
            ["id" => 243 , "name"=>"Asia/Irkutsk"],
            ["id" => 244 , "name"=>"Asia/Jakarta"],
            ["id" => 245 , "name"=>"Asia/Jayapura"],
            ["id" => 246 , "name"=>"Asia/Jerusalem"],
            ["id" => 247 , "name"=>"Asia/Kabul"],
            ["id" => 248 , "name"=>"Asia/Kamchatka"],
            ["id" => 249 , "name"=>"Asia/Karachi"],
            ["id" => 250 , "name"=>"Asia/Kathmandu"],
            ["id" => 251 , "name"=>"Asia/Khandyga"],
            ["id" => 252 , "name"=>"Asia/Kolkata"],
            ["id" => 253 , "name"=>"Asia/Krasnoyarsk"],
            ["id" => 254 , "name"=>"Asia/Kuala_Lumpur"],
            ["id" => 255 , "name"=>"Asia/Kuching"],
            ["id" => 256 , "name"=>"Asia/Kuwait"],
            ["id" => 257 , "name"=>"Asia/Macau"],
            ["id" => 258 , "name"=>"Asia/Magadan"],
            ["id" => 259 , "name"=>"Asia/Makassar"],
            ["id" => 260 , "name"=>"Asia/Manila"],
            ["id" => 261 , "name"=>"Asia/Muscat"],
            ["id" => 262 , "name"=>"Asia/Nicosia"],
            ["id" => 263 , "name"=>"Asia/Novokuznetsk"],
            ["id" => 264 , "name"=>"Asia/Novosibirsk"],
            ["id" => 265 , "name"=>"Asia/Omsk"],
            ["id" => 266 , "name"=>"Asia/Oral"],
            ["id" => 267 , "name"=>"Asia/Phnom_Penh"],
            ["id" => 268 , "name"=>"Asia/Pontianak"],
            ["id" => 269 , "name"=>"Asia/Pyongyang"],
            ["id" => 270 , "name"=>"Asia/Qatar"],
            ["id" => 271 , "name"=>"Asia/Qostanay"],
            ["id" => 272 , "name"=>"Asia/Qyzylorda"],
            ["id" => 273 , "name"=>"Asia/Riyadh"],
            ["id" => 274 , "name"=>"Asia/Sakhalin"],
            ["id" => 275 , "name"=>"Asia/Samarkand"],
            ["id" => 276 , "name"=>"Asia/Seoul"],
            ["id" => 277 , "name"=>"Asia/Shanghai"],
            ["id" => 278 , "name"=>"Asia/Singapore"],
            ["id" => 279 , "name"=>"Asia/Srednekolymsk"],
            ["id" => 280 , "name"=>"Asia/Taipei"],
            ["id" => 281 , "name"=>"Asia/Tashkent"],
            ["id" => 282 , "name"=>"Asia/Tbilisi"],
            ["id" => 283 , "name"=>"Asia/Tehran"],
            ["id" => 284 , "name"=>"Asia/Thimphu"],
            ["id" => 285 , "name"=>"Asia/Tokyo"],
            ["id" => 286 , "name"=>"Asia/Tomsk"],
            ["id" => 287 , "name"=>"Asia/Ulaanbaatar"],
            ["id" => 288 , "name"=>"Asia/Urumqi"],
            ["id" => 289 , "name"=>"Asia/Ust-Nera"],
            ["id" => 290 , "name"=>"Asia/Vientiane"],
            ["id" => 291 , "name"=>"Asia/Vladivostok"],
            ["id" => 292 , "name"=>"Asia/Yakutsk"],
            ["id" => 293 , "name"=>"Asia/Yangon"],
            ["id" => 294 , "name"=>"Asia/Yekaterinburg"],
            ["id" => 295 , "name"=>"Asia/Yerevan"],
            ["id" => 296 , "name"=>"Atlantic/Azores"],
            ["id" => 297 , "name"=>"Atlantic/Bermuda"],
            ["id" => 298 , "name"=>"Atlantic/Canary"],
            ["id" => 299 , "name"=>"Atlantic/Cape_Verde"],
            ["id" => 300 , "name"=>"Atlantic/Faroe"],
            ["id" => 301 , "name"=>"Atlantic/Madeira"],
            ["id" => 302 , "name"=>"Atlantic/Reykjavik"],
            ["id" => 303 , "name"=>"Atlantic/South_Georgia"],
            ["id" => 304 , "name"=>"Atlantic/St_Helena"],
            ["id" => 305 , "name"=>"Atlantic/Stanley"],
            ["id" => 306 , "name"=>"Australia/Adelaide"],
            ["id" => 307 , "name"=>"Australia/Brisbane"],
            ["id" => 308 , "name"=>"Australia/Broken_Hill"],
            ["id" => 309 , "name"=>"Australia/Darwin"],
            ["id" => 310 , "name"=>"Australia/Eucla"],
            ["id" => 311 , "name"=>"Australia/Hobart"],
            ["id" => 312 , "name"=>"Australia/Lindeman"],
            ["id" => 313 , "name"=>"Australia/Lord_Howe"],
            ["id" => 314 , "name"=>"Australia/Melbourne"],
            ["id" => 315 , "name"=>"Australia/Perth"],
            ["id" => 316 , "name"=>"Australia/Sydney"],
            ["id" => 317 , "name"=>"Europe/Amsterdam"],
            ["id" => 318 , "name"=>"Europe/Andorra"],
            ["id" => 319 , "name"=>"Europe/Astrakhan"],
            ["id" => 320 , "name"=>"Europe/Athens"],
            ["id" => 321 , "name"=>"Europe/Belgrade"],
            ["id" => 322 , "name"=>"Europe/Berlin"],
            ["id" => 323 , "name"=>"Europe/Bratislava"],
            ["id" => 324 , "name"=>"Europe/Brussels"],
            ["id" => 325 , "name"=>"Europe/Bucharest"],
            ["id" => 326 , "name"=>"Europe/Budapest"],
            ["id" => 327 , "name"=>"Europe/Busingen"],
            ["id" => 328 , "name"=>"Europe/Chisinau"],
            ["id" => 329 , "name"=>"Europe/Copenhagen"],
            ["id" => 330 , "name"=>"Europe/Dublin"],
            ["id" => 331 , "name"=>"Europe/Gibraltar"],
            ["id" => 332 , "name"=>"Europe/Guernsey"],
            ["id" => 333 , "name"=>"Europe/Helsinki"],
            ["id" => 334 , "name"=>"Europe/Isle_of_Man"],
            ["id" => 335 , "name"=>"Europe/Istanbul"],
            ["id" => 336 , "name"=>"Europe/Jersey"],
            ["id" => 337 , "name"=>"Europe/Kaliningrad"],
            ["id" => 338 , "name"=>"Europe/Kiev"],
            ["id" => 339 , "name"=>"Europe/Kirov"],
            ["id" => 340 , "name"=>"Europe/Lisbon"],
            ["id" => 341 , "name"=>"Europe/Ljubljana"],
            ["id" => 342 , "name"=>"Europe/London"],
            ["id" => 343 , "name"=>"Europe/Luxembourg"],
            ["id" => 344 , "name"=>"Europe/Madrid"],
            ["id" => 345 , "name"=>"Europe/Malta"],
            ["id" => 346 , "name"=>"Europe/Mariehamn"],
            ["id" => 347 , "name"=>"Europe/Minsk"],
            ["id" => 348 , "name"=>"Europe/Monaco"],
            ["id" => 349 , "name"=>"Europe/Moscow"],
            ["id" => 350 , "name"=>"Europe/Oslo"],
            ["id" => 351 , "name"=>"Europe/Paris"],
            ["id" => 352 , "name"=>"Europe/Podgorica"],
            ["id" => 353 , "name"=>"Europe/Prague"],
            ["id" => 354 , "name"=>"Europe/Riga"],
            ["id" => 355 , "name"=>"Europe/Rome"],
            ["id" => 356 , "name"=>"Europe/Samara"],
            ["id" => 357 , "name"=>"Europe/San_Marino"],
            ["id" => 358 , "name"=>"Europe/Sarajevo"],
            ["id" => 359 , "name"=>"Europe/Saratov"],
            ["id" => 360 , "name"=>"Europe/Simferopol"],
            ["id" => 361 , "name"=>"Europe/Skopje"],
            ["id" => 362 , "name"=>"Europe/Sofia"],
            ["id" => 363 , "name"=>"Europe/Stockholm"],
            ["id" => 364 , "name"=>"Europe/Tallinn"],
            ["id" => 365 , "name"=>"Europe/Tirane"],
            ["id" => 366 , "name"=>"Europe/Ulyanovsk"],
            ["id" => 367 , "name"=>"Europe/Uzhgorod"],
            ["id" => 368 , "name"=>"Europe/Vaduz"],
            ["id" => 369 , "name"=>"Europe/Vatican"],
            ["id" => 370 , "name"=>"Europe/Vienna"],
            ["id" => 371 , "name"=>"Europe/Vilnius"],
            ["id" => 372 , "name"=>"Europe/Volgograd"],
            ["id" => 373 , "name"=>"Europe/Warsaw"],
            ["id" => 374 , "name"=>"Europe/Zagreb"],
            ["id" => 375 , "name"=>"Europe/Zaporozhye"],
            ["id" => 376 , "name"=>"Europe/Zurich"],
            ["id" => 378 , "name"=>"Indian/Antananarivo"],
            ["id" => 379 , "name"=>"Indian/Chagos"],
            ["id" => 380 , "name"=>"Indian/Christmas"],
            ["id" => 381 , "name"=>"Indian/Cocos"],
            ["id" => 382 , "name"=>"Indian/Comoro"],
            ["id" => 383 , "name"=>"Indian/Kerguelen"],
            ["id" => 384 , "name"=>"Indian/Mahe"],
            ["id" => 385, "name"=>"Indian/Maldives"],
            ["id" => 386 , "name"=>"Indian/Mauritius"],
            ["id" => 387 , "name"=>"Indian/Mayotte"],
            ["id" => 388 , "name"=>"Indian/Reunion"],
            ["id" => 389 , "name"=>"Pacific/Apia"],
            ["id" => 390 , "name"=>"Pacific/Auckland"],
            ["id" => 391 , "name"=>"Pacific/Bougainville"],
            ["id" => 392 , "name"=>"Pacific/Chatham"],
            ["id" => 393 , "name"=>"Pacific/Chuuk"],
            ["id" => 394 , "name"=>"Pacific/Easter"],
            ["id" => 395 , "name"=>"Pacific/Efate"],
            ["id" => 396 , "name"=>"Pacific/Fakaofo"],
            ["id" => 397 , "name"=>"Pacific/Fiji"],
            ["id" => 398 , "name"=>"Pacific/Funafuti"],
            ["id" => 399 , "name"=>"Pacific/Galapagos"],
            ["id" => 400 , "name"=>"Pacific/Gambier"],
            ["id" => 401 , "name"=>"Pacific/Guadalcanal"],
            ["id" => 402 , "name"=>"Pacific/Guam"],
            ["id" => 403 , "name"=>"Pacific/Honolulu"],
            ["id" => 404 , "name"=>"Pacific/Kanton"],
            ["id" => 405 , "name"=>"Pacific/Kiritimati"],
            ["id" => 406 , "name"=>"Pacific/Kosrae"],
            ["id" => 407 , "name"=>"Pacific/Kwajalein"],
            ["id" => 408 , "name"=>"Pacific/Majuro"],
            ["id" => 409 , "name"=>"Pacific/Marquesas"],
            ["id" => 410 , "name"=>"Pacific/Midway"],
            ["id" => 411 , "name"=>"Pacific/Nauru"],
            ["id" => 412 , "name"=>"Pacific/Niue"],
            ["id" => 413 , "name"=>"Pacific/Norfolk"],
            ["id" => 414 , "name"=>"Pacific/Noumea"],
            ["id" => 415 , "name"=>"Pacific/Pago_Pago"],
            ["id" => 416 , "name"=>"Pacific/Palau"],
            ["id" => 417 , "name"=>"Pacific/Pitcairn"],
            ["id" => 418 , "name"=>"Pacific/Pohnpei"],
            ["id" => 419 , "name"=>"Pacific/Port_Moresby"],
            ["id" => 420 , "name"=>"Pacific/Rarotonga"],
            ["id" => 421 , "name"=>"Pacific/Saipan"],
            ["id" => 422 , "name"=>"Pacific/Tahiti"],
            ["id" => 423 , "name"=>"Pacific/Tarawa"],
            ["id" => 424 , "name"=>"Pacific/Tongatapu"],
            ["id" => 425 , "name"=>"Pacific/Wake"],
            ["id" => 426 , "name"=>"Pacific/Wallis"],
            ["id" => 427 , "name"=>"UTC"],
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Timezone::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        foreach( $timezones as $timezone){
            Timezone::create($timezone);
        }
    }
}
